baseURL = 'https://donatomartinelli.github.io/'
languageCode = 'it-it'
title = 'Donato Martinelli'
theme = 'm10c'

[params]
  author = "Donato Martinelli"
  # Usiamo  per mandare a capo la biografia senza che Hugo la spezzi
  description = "Math BSc student at Unibas. Interested in Math, Poker, and Economics."

[[params.social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/donato-martinelli-795542267/"

[[params.social]]
  name = "Curriculum"
  url = "/cv.pdf"

[[params.social]]
  name = "GitHub"
  url = "https://github.com/donatomartinelli"

[params.style]
  darkestColor = "#000000"   # Sfondo generale del sito (Nero puro)
  darkColor = "#000000"      # Sfondo della barra laterale (Nero puro)
  primaryColor = "#ffffff"   # Colore al passaggio del mouse
  lightColor = "#e6e6e6"     # Colore del testo
  lightestColor = "#ffffff"  # Colore dei titoli

[menu]
  [[menu.main]]
    identifier = "matematica"
    name = "MATEMATICA"
    url = "/projects/matematica/"
    weight = 10
  [[menu.main]]
    identifier = "Mental Math"
    name = "Mental Math"
    url = "/projects/mentalmath/"
    weight = 20
  [[menu.main]]
    identifier = "Habit Tracker"
    name = "Habit Tracker"
    url = "/projects/habittracker/"
    weight = 30